# Generated by Django 5.0.3 on 2024-03-25 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facts', models.TextField()),
                ('issues', models.TextField()),
                ('arguments', models.TextField()),
                ('reference_materials', models.TextField()),
            ],
        ),
    ]
